### ISSUE TITLE
无法获取到 CanvasContext2D

### ISSUE THREAD

**Issue by yr600123** [buuing/lucky-canvas#158]
- 你当前是什么框架(必填)：
- vue2.5.2

- 你使用的是哪个包(必填)：
- npm 安装的  script 标签引入后错误一样

- 你当前插件的版本(必填)：0.5

- 详细描述你的bug：
- 插件载入后 控制台报三个错

- 问题代码(重要)：
  1.[Vue warn]: `createElement()` has been called outside of render function.
  2.无法获取到 CanvasContext2D index.umd.js:962 
  3.Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'translate')
```
// 粘贴你的代码
```项目不好拆分.就只使用了官网的第一步

**Comment by buuing** [comment]
你的代码是如何使用的, 贴出来我看看

**Comment by buuing** [comment]
你确定下面这个demo无法使用吗?

```html
<div id="app">
  <!-- 大转盘抽奖简易demo -->
  <lucky-wheel
    width="200px"
    height="200px"
    :blocks="blocks"
    :prizes="prizes"
  />
</div>

<!-- vuejs 要在前面引入, 使用你自己本地的 vuejs 即可 -->
<script src="./vue2.js"></script>
<!-- 为了兼容 vue2.x 需要同时引入以下这三个 CDN 链接 -->
<script src="https://cdn.jsdelivr.net/npm/@vue/composition-api@1.2.4/dist/vue-composition-api.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-demi@0.11.4/lib/index.iife.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@lucky-canvas/vue/dist/index.umd.min.js"></script>
<script>
  new Vue({
    el: '#app',
    data () {
      return {
        blocks: [{ padding: '10px', background: '#869cfa' }],
        prizes: [
          { fonts: [{ text: '0' }], background: '#e9e8fe' },
          { fonts: [{ text: '1' }], background: '#b8c5f2' },
          { fonts: [{ text: '2' }], background: '#e9e8fe' },
          { fonts: [{ text: '3' }], background: '#b8c5f2' },
          { fonts: [{ text: '4' }], background: '#e9e8fe' },
          { fonts: [{ text: '5' }], background: '#b8c5f2' },
        ]
      }
    }
  })
</script>
```

**Comment by yr600123** [comment]
感谢你这么快回复.我刚才简化了下我的代码.index.vue文件如下
```
<template>
  <div id="app">
    <lucky-wheel
    width="200px"
    height="200px"
    :blocks="blocks"
    :prizes="prizes"/>
  </div>
</template>
<script>
import "assets/css/common.css";
import "./index.css";
import vueSeamlessScroll from "components/myClass";
export default {
  data() {
    return {
     
       blocks: [{ padding: '10px', background: '#869cfa' }],
      prizes: [
        { fonts: [{ text: '0' }], background: '#e9e8fe' },
        { fonts: [{ text: '1' }], background: '#b8c5f2' },
        { fonts: [{ text: '2' }], background: '#e9e8fe' },
        { fonts: [{ text: '3' }], background: '#b8c5f2' },
        { fonts: [{ text: '4' }], background: '#e9e8fe' },
        { fonts: [{ text: '5' }], background: '#b8c5f2' },
      ]
    };
  },
  filters: {
   
  },
  watch: {
    day_active(val) {
      // this.getRank(val);
    },
  },
  //已成功挂载，相当ready()
  mounted() {},
  components: {
    vueSeamlessScroll
    // LuckyWheel,
    // LuckyWheel
  },
  methods: {},
};
</script>

<style>

</style>
```
index.js如下
```
import Vue from 'vue'
import App from './index.vue'
import $ from 'jquery'
// import VueLuckyCanvas from '@lucky-canvas/vue'
// Vue.use(VueLuckyCanvas)
import VueLuckyCanvas from '@lucky-canvas/vue'
Vue.use(VueLuckyCanvas)
new Vue({
  render: h => h(App)
}).$mount('#app')
```
还是报一样的错 我感觉是包和我本地的包有冲突

**Comment by buuing** [comment]
我试试

**Comment by buuing** [comment]
你输入这个命令试试
`npm i composition-api@1.2.4`
安装之后重新启动

**Comment by yr600123** [comment]
好的 我试试

**Comment by yr600123** [comment]
找不到这个版本

**Comment by buuing** [comment]
> 找不到这个版本

哦哦, 刚刚写错了
`npm i @vue/composition-api@1.2.4`

**Comment by yr600123** [comment]
我好像解决了 不报错了
要饮用这个库
```
import VueCompositionAPI from '@vue/composition-api'
Vue.use(VueCompositionAPI)
```

**Comment by buuing** [comment]
ok, 我晚上找个vue2.5试试

**Comment by buuing** [comment]
奇怪, 我安装了一个vue-cli@2.x, 然后创建了一个vue2.5.2的空项目, 发现可以运行无报错, 不需要手动use(VueCompositionAPI)

**Comment by buuing** [comment]
你加一下我的微信:`new_ldq`

**Comment by songjingxiaoyu** [comment]
我也遇到这个问题了，检查一遍是自己代码有问题，所以感觉这个大概率是自己写的代码有问题，不是插件问题，

**Comment by whb1013** [comment]
Cannot read properties of undefined (reading 'translate')
TypeError: Cannot read properties of undefined (reading 'translate')
    at o.resize (webpack-internal:///./node_modules/.store/lucky-canvas@1.7.27/node_modules/lucky-canvas/dist/index.esm.js:23:14114)
    at eval (webpack-internal:///./node_modules/.store/lucky-canvas@1.7.27/node_modules/lucky-canvas/dist/index.esm.js:23:7754)
    at eval (webpack-internal:///./node_modules/.store/lucky-canvas@1.7.27/node_modules/lucky-canvas/dist/index.esm.js:23:7691)

怎么问题
